name: .NET

on:
  push:
    branches: [universal]
  pull_request:
    branches: [universal]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Clean 1
        run: dotnet clean WFBot.sln --configuration "Windows Release" && dotnet nuget locals all --clear
      - name: Clean 2
        run: dotnet clean WFBot.sln --configuration "Linux Release" && dotnet nuget locals all --clear
      - name: Restore dependencies
        run: dotnet restore

      - name: Windows Build
        run: dotnet publish WFBot -c "Windows Release" -o WindowsPublish --self-contained false
        env:
          OFFICIAL_BUILD: official
      - name: Linux Build
        run: dotnet publish WFBot -c "Linux Release" -o LinuxPublish --self-contained false
        env:
          OFFICIAL_BUILD: official
      - name: Mirai Connector Build
        run: dotnet publish Connectors/MiraiHTTPConnector -c "Linux Release" -o MiraiConnector --self-contained false
        env:
          OFFICIAL_BUILD: official

      - name: Pre Run Windows
        run: dotnet WindowsPublish/WFBot.dll --skip-press-any-key
      - name: Pre Run Linux
        run: dotnet LinuxPublish/WFBot.dll --skip-press-any-key

      - name: Zip Windows Release
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./WindowsPublish/
          pathTarget: WFBot-Windows.7z
      - name: Zip Linux Release
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./LinuxPublish/
          pathTarget: WFBot-Linux.7z
      - name: Zip Mirai Connector
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathTarget: WFBot-MiraiConnector.7z
          pathSource: ./MiraiConnector/
      - name: Upload Windows
        uses: actions/upload-artifact@v2
        with:
          name: WFBot Windows
          path: ./WFBot-Windows.7z
          retention-days: 30
      - name: Upload Linux
        uses: actions/upload-artifact@v2
        with:
          name: WFBot Linux
          path: ./WFBot-Linux.7z
          retention-days: 30
      - name: Upload MiraiHTTPConnector
        uses: actions/upload-artifact@v2
        with:
          name: WFBot Mirai Connector
          path: ./WFBot-MiraiConnector.7z
          retention-days: 30
