name: .NET

on:
  push:
    branches: [ universal ]
  pull_request:
    branches: [ universal ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Windows Build
      run: dotnet publish WFBot -c "Windows Release" -o WindowsPublish --self-contained false --no-restore
    - name: Linux Build
      run: dotnet publish WFBot -c "Linux Release" -o LinuxPublish --self-contained false --no-restore
    - name: Mirai Connector Build
      run: dotnet publish MiraiHTTPConnector -c "Linux Release" -o MiraiConnector --self-contained false --no-restore
    - name: Zip Windows Release
      uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a -t7z -mx=9 WFBot-Windows.7z ./WindowsPublish/
    - name: Zip Linux Release
      uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a -t7z -mx=9 WFBot-Linux.7z ./LinuxPublish/
    - name: Zip Mirai Connector
      uses: edgarrc/action-7z@v1.0.4
      with:
        args: 7z a -t7z -mx=9 WFBot-MiraiConnector.7z ./MiraiConnector/
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: WFBot
        path: |
          ./WFBot-Windows.7z
          ./WFBot-Linux.7z
          ./WFBot-MiraiHTTPConnector.7z
        retention-days: 30
