name: .NET

on:
  push:
    branches: [ universal ]
  pull_request:
    branches: [ universal ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish WFBot -c "Windows Release" -o publish --self-contained false --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
